[manager]
cwd = { fg = "#98C379" }

# Hovered
hovered = { bg = "#282C34" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#E06C75", italic = true, underline = true }
find_position = { fg = "#E5C07B", italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied = { fg = "#ABB2BF", bg = "#98C379" }
marker_cut = { fg = "#ABB2BF", bg = "#E06C75" }
marker_marked = { fg = "#ABB2BF", bg = "#56B6C2" }
marker_selected = { fg = "#ABB2BF", bg = "#E5C07B" }

# Tab
tab_active = { bg = "#282C34", fg = "#61AFEF" }
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "#98C379", bg = "#282C34" }
count_cut = { fg = "#E06C75", bg = "#282C34" }
count_selected = { fg = "#98C379", bg = "#282C34" }

# Border
border_symbol = "│"
border_style = { fg = "#282C34" }


[mode]
normal_main = { fg = "#282C34", bg = "#61AFEF", bold = true }
normal_alt = { fg = "#282C34", bg = "#ABB2BF", bold = false }
select_main = { fg = "#282C34", bg = "#98C379", bold = true }
select_alt = { fg = "#282C34", bg = "#ABB2BF", bold = false }
unset_main = { fg = "#282C34", bg = "#E06C75", bold = true }
unset_alt = { fg = "#282C34", bg = "#ABB2BF", bold = false }

[status]
overall = {}
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "#ABB2BF" }
perm_type = { fg = "#61AFEF" }
perm_read = { fg = "#E06C75" }
perm_write = { fg = "#E5C07B" }
perm_exec = { fg = "#98C379" }


# Progress
progress_label = { fg = "#ABB2BF", bold = true }
progress_normal = { fg = "#98C379", bg = "#282C34" }
progress_error = { fg = "#E06C75", bg = "#282C34" }


[which]
mask = { bg = "#282C34" }
cand = { fg = "#98C379" }
rest = { fg = "#ABB2BF" }
desc = { fg = "#E5C07B" }
separator = "  "
separator_style = { fg = "#ABB2BF" }


[confirm]
border = { fg = "#61AFEF" }
title = { fg = "#61AFEF" }

[spot]
border = { fg = "#61AFEF" }
title = { fg = "#61AFEF" }
tbl_col = { fg = "#61AFEF" }
tbl_cell = { fg = "#E5C07B", reversed = true }


[notify]
title_info = { fg = "#98C379" }
title_warn = { fg = "#E5C07B" }
title_error = { fg = "#E06C75" }

[pick]
border = { fg = "#61AFEF" }
active = { fg = "#C678DD", bold = true }
inactive = {}


[input]
border = { fg = "#61AFEF" }


[cmp]
border = { fg = "#61AFEF" }


[tasks]
border = { fg = "#61AFEF" }
hovered = { fg = "#C678DD", underline = true }


[help]
on = { fg = "#98C379" }
run = { fg = "#E5C07B" }
hovered = { reversed = true, bold = true }
footer = { fg = "#ABB2BF", bg = "#000000" }


[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#E5C07B" },

    # Media
    { mime = "video/*", fg = "#E06C75" },
    { mime = "audio/*", fg = "#E06C75" },

    # Archives
    { mime = "application/zip", fg = "#C678DD" },
    { mime = "application/x-tar", fg = "#C678DD" },
    { mime = "application/x-bzip*", fg = "#C678DD" },
    { mime = "application/x-bzip2", fg = "#C678DD" },
    { mime = "application/x-7z-compressed", fg = "#C678DD" },
    { mime = "application/x-rar", fg = "#C678DD" },
    { mime = "application/x-xz", fg = "#C678DD" },

    # Documents
    { mime = "application/doc", fg = "#98C379" },
    { mime = "application/pdf", fg = "#98C379" },
    { mime = "application/rtf", fg = "#98C379" },
    { mime = "application/vnd.*", fg = "#98C379" },

    # Fallback
    { name = "*", fg = "#ABB2BF" },
    { name = "*/", fg = "#61AFEF" },
]